version: "3"
services:
  node:
    image: tjamet/photo-frontend-node
    build: .
    networks:
      - web
    deploy:
      replicas: 2
      labels:
        - "traefik.port=3000"
        - "traefik.backend=www.thib-o.eu"
        - "traefik.frontend.rule=Host:www.thib-o.eu"
    labels:
      - "traefik.port=3000"
      - "traefik.backend=www.thib-o.eu"
      - "traefik.frontend.rule=Host:www.thib-o.eu"
networks:
  web:
    external:
      name: infra_webgateway
